language: java
jdk:
  - openjdk11

branches:
  only:
    - master
    - main

# Travs CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: './gradlew clean build'

before_deploy:
  - zip -r springboot2-webservice *
  - mkdir -p deploy
  - mv springboot2-webservice.zip deploy/springboot2-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: jeonghyeon-springboot-build # S3버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true
    on:
      all_branches: true
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: jeonghyeon-springboot-build
    key: springboot2-webservice.zip

    bundle_type: zip
    application: springboot2-webservice
    deployment_group: springboot2-webservice-group
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      all_branches: true

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - 'givejeong2468@gmail.com'

# 배포 테스트 1(특수문자 키 X, 지역 변경)
